name: "Run Unit Tests"
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Create artifacts directory
      run: |
        mkdir artifacts
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Run tests
      run: |
        python -m unittest -vv 2> >(tee artifacts/test_results.txt)
    - uses: actions/upload-artifact@v1
      with:
        name: Artifacts
        path: artifacts
